language: rust
cache: cargo
rust:
  - stable
os: linux

# always test things that aren't pushes (like PRs)
# never test tags or pushes to non-master branches (wait for PR)
if: type != push OR (tag IS blank AND branch = master)

jobs:
  fast_finish: true
  include:
    - stage: check
      script: cargo check --all-targets
      rust: stable
    - stage: test
      script: cargo test
    - stage: lint
      install:
        - rustup component add rustfmt clippy
      script:
        - cargo fmt -v -- --check
        - cargo clippy --all-features --all-targets -- -D warnings

stages:
  - check
  - test
  - lint
